const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const S=window.STRATEGIES||[], L=window.LEVERAGE||[], T=window.TRADES||[], M=window.LAB_META||{}; S.sort((a,b)=>Number(b.globalScore||0)-Number(a.globalScore||0)).forEach((x,i)=>x.rank=i+1);
const euro=x=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:2}).format(Number(x||0));
const num=(x,d=1)=>new Intl.NumberFormat('it-IT',{maximumFractionDigits:d}).format(Number(x||0));
const pct=x=>`${num(x,2)}%`; const cls=x=>Number(x)>=0?'pos':'neg';
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const titles={dashboard:'Research Dashboard',matrix:'Strategy Matrix',detail:'Strategy Detail',leverage:'Leverage Lab',trades:'Trade Explorer',quality:'Data Quality'};
let charts={};
function chart(id,type,data,options={}){if(charts[id])charts[id].destroy();const el=$(id);if(!el||!window.Chart)return;charts[id]=new Chart(el,{type,data,options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:'#a9c0c5'}}},scales:type==='doughnut'?{}:{x:{ticks:{color:'#75949b'},grid:{color:'#11242b'}},y:{ticks:{color:'#75949b'},grid:{color:'#11242b'}}},...options}})}
function show(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#title').textContent=titles[v]||v;if(v==='detail')renderDetail($('#strategySelect').value);if(v==='leverage')renderLeverage($('#levStrategy').value);}
function kpi(label,value,sub,c=''){return `<div class="kpi"><span>${esc(label)}</span><b class="${c}">${value}</b><small>${esc(sub)}</small></div>`}
function bootNav(){$$('.nav').forEach(b=>b.onclick=()=>show(b.dataset.view));$$('[data-jump]').forEach(b=>b.onclick=()=>show(b.dataset.jump));}
function renderDashboard(){const best=[...S].sort((a,b)=>a.rank-b.rank)[0], profitable=S.filter(x=>x.netPnL>0).length, bestOOS=[...S].sort((a,b)=>b.oosReturnPct-a.oosReturnPct)[0], robust=[...S].sort((a,b)=>b.robustnessScore-a.robustnessScore)[0];$('#bestScore').textContent=num(best.globalScore,1);$('#kpis').innerHTML=kpi('Best strategy',best.strategy_id,best.name)+kpi('Ending capital',euro(best.endingCapital),'From €50',cls(best.netPnL))+kpi('Best OOS',pct(bestOOS.oosReturnPct),bestOOS.strategy_id,cls(bestOOS.oosReturnPct))+kpi('Best robustness',num(robust.robustnessScore,1)+'/100',robust.strategy_id)+kpi('Profitable',`${profitable}/${S.length}`,'After modeled costs',profitable>S.length/2?'pos':'neg');const top=[...S].sort((a,b)=>b.globalScore-a.globalScore).slice(0,10);chart('#scoreChart','bar',{labels:top.map(x=>x.strategy_id),datasets:[{label:'Global score',data:top.map(x=>x.globalScore),backgroundColor:'#62e7d3'}]});chart('#riskChart','scatter',{datasets:[{label:'Strategies',data:S.map(x=>({x:x.maxDrawdownPct,y:x.returnPct,label:x.strategy_id})),backgroundColor:'#72b9ff'}]},{plugins:{tooltip:{callbacks:{label:c=>`${c.raw.label}: Return ${pct(c.raw.y)} · DD ${pct(c.raw.x)}`}}}});$('#leaders').innerHTML=top.slice(0,6).map(x=>`<div class="leader" data-id="${x.strategy_id}"><b>${x.strategy_id} · ${esc(x.name)}</b><small>${esc(x.family)} · ${x.timeframe}</small><div class="score">${num(x.globalScore,1)}/100</div><small>Return ${pct(x.returnPct)} · DD ${pct(x.maxDrawdownPct)} · OOS ${pct(x.oosReturnPct)}</small></div>`).join('');$$('.leader').forEach(x=>x.onclick=()=>{$('#strategySelect').value=x.dataset.id;show('detail')});}
function setupFilters(){[...new Set(S.map(x=>x.family))].sort().forEach(f=>$('#family').insertAdjacentHTML('beforeend',`<option>${esc(f)}</option>`));const opts=S.map(x=>`<option value="${x.strategy_id}">${x.strategy_id} · ${esc(x.name)}</option>`).join('');$('#strategySelect').innerHTML=opts;$('#levStrategy').innerHTML=opts;['search','family','sort'].forEach(id=>$('#'+id).addEventListener('input',renderMatrix));$('#strategySelect').onchange=()=>renderDetail($('#strategySelect').value);$('#levStrategy').onchange=()=>renderLeverage($('#levStrategy').value);$('#tradeSearch').addEventListener('input',renderTrades);$('#side').addEventListener('change',renderTrades);}
function renderMatrix(){let rows=[...S],q=$('#search').value.toLowerCase(),fam=$('#family').value,sort=$('#sort').value;if(q)rows=rows.filter(x=>(x.strategy_id+' '+x.name+' '+x.family).toLowerCase().includes(q));if(fam)rows=rows.filter(x=>x.family===fam);rows.sort((a,b)=>sort==='rank'?a.rank-b.rank:sort==='maxDrawdownPct'?a[sort]-b[sort]:b[sort]-a[sort]);$('#matrixBody').innerHTML=rows.map(x=>`<tr data-id="${x.strategy_id}"><td>${x.rank}</td><td><b>${x.strategy_id}</b><br><small>${esc(x.name)}</small></td><td>${esc(x.family)}</td><td>${x.timeframe}</td><td class="${cls(x.returnPct)}">${pct(x.returnPct)}</td><td class="${cls(x.netPnL)}">${euro(x.netPnL)}</td><td>${num(x.trades,0)}</td><td>${pct(x.winRate)}</td><td>${num(x.profitFactor,2)}</td><td class="neg">${pct(x.maxDrawdownPct)}</td><td class="${cls(x.netEdgePerTradePct)}">${pct(x.netEdgePerTradePct)}</td><td class="${cls(x.oosReturnPct)}">${pct(x.oosReturnPct)}</td><td>${num(x.robustnessScore,1)}</td><td>${num(x.statisticalConfidenceScore,1)}</td><td><span class="score-pill">${num(x.globalScore,1)}</span></td></tr>`).join('');$$('#matrixBody tr').forEach(r=>r.onclick=()=>{$('#strategySelect').value=r.dataset.id;show('detail')});}
function renderDetail(id){const x=S.find(s=>s.strategy_id===id)||S[0];if(!x)return;$('#strategyHero').innerHTML=`<div class="hero"><div><p class="eyebrow">${esc(x.family)} · ${x.timeframe}</p><h2>${x.strategy_id} · ${esc(x.name)}</h2><p>${esc(x.description)}</p></div><div class="hero-score"><b>${num(x.globalScore,1)}</b><small>Global score</small></div></div>`;$('#detailKpis').innerHTML=kpi('Ending capital',euro(x.endingCapital),'Starting €50',cls(x.netPnL))+kpi('Net edge / trade',pct(x.netEdgePerTradePct),'After costs',cls(x.netEdgePerTradePct))+kpi('Max drawdown',pct(x.maxDrawdownPct),`${num(x.trades,0)} trades`,'neg')+kpi('Profit factor',num(x.profitFactor,2),'Full Potential',x.profitFactor>=1?'pos':'neg')+kpi('OOS return',pct(x.oosReturnPct),`${num(x.oosTrades,0)} OOS trades`,cls(x.oosReturnPct));const profileRows=[['Trades/day',num(x.tradesPerDay,2)],['Average leverage',num(x.avgLeverage,2)+'×'],['Max margin utilization',pct(x.maxMarginUtilizationPct)],['Total execution costs',euro(x.totalCosts)],['Gross edge / trade',pct(x.grossEdgePerTradePct)],['Cost / gross profit',pct(x.costGrossProfitRatio)],['Capital survival',num(x.capitalSurvival,1)+'/100']];if(x.components&&x.components.length)profileRows.push(['Components',x.components.join(' + ')],['Ensemble rule',x.ensemble_rule||'Directional consensus']);profileRows.push(['Warnings',x.warnings||'None']);$('#profile').innerHTML=profileRows.map(([a,b])=>`<div class="metric-row"><span>${esc(a)}</span><b>${esc(b)}</b></div>`).join('');chart('#lsChart','bar',{labels:['LONG','SHORT'],datasets:[{label:'Net PnL €',data:[x.longPnL,x.shortPnL],backgroundColor:['#62e7d3','#72b9ff']}]});const scores=[['Statistical confidence',x.statisticalConfidenceScore],['Parameter stability',x.parameterStabilityScore],['OOS',x.oosScore],['Robustness',x.robustnessScore],['Fair Fight signal',x.fairFightSignalScore]];$('#scoreGrid').innerHTML=scores.map(([a,b])=>`<div class="score-card"><span>${esc(a)}</span><b>${num(b,1)}/100</b></div>`).join('');}
function renderLeverage(id){const rows=L.filter(x=>x.strategyId===id);if(!rows.length){$('#levKpis').innerHTML=kpi('Leverage data','Not available','No leverage rows for this strategy');$('#levBody').innerHTML='';return;}const best=[...rows].sort((a,b)=>((b.returnPct-b.maxDrawdownPct)-(a.returnPct-a.maxDrawdownPct)))[0];$('#levKpis').innerHTML=kpi('Efficiency candidate',best.leverage,'Return − drawdown heuristic')+kpi('Return',pct(best.returnPct),'Candidate',cls(best.returnPct))+kpi('Max DD',pct(best.maxDrawdownPct),'Candidate','neg')+kpi('Capital survival',num(best.capitalSurvival,1)+'/100','Candidate')+kpi('Max margin use',pct(best.maxMarginUtilizationPct),'Candidate');chart('#levReturn','bar',{labels:rows.map(x=>x.leverage),datasets:[{label:'Return %',data:rows.map(x=>x.returnPct),backgroundColor:'#62e7d3'}]});chart('#levDd','bar',{labels:rows.map(x=>x.leverage),datasets:[{label:'Max DD %',data:rows.map(x=>x.maxDrawdownPct),backgroundColor:'#ff7a88'}]});$('#levBody').innerHTML=rows.map(x=>`<tr><td>${esc(x.leverage)}</td><td>${euro(x.endingCapital)}</td><td class="${cls(x.returnPct)}">${pct(x.returnPct)}</td><td class="neg">${pct(x.maxDrawdownPct)}</td><td>${num(x.sharpe,2)}</td><td>${num(x.sortino,2)}</td><td>${num(x.capitalSurvival,1)}/100</td><td>${pct(x.maxMarginUtilizationPct)}</td></tr>`).join('');}
function renderTrades(){let q=$('#tradeSearch').value.toLowerCase(),side=$('#side').value,rows=T.filter(x=>(!q||(x.strategy+' '+x.strategyId+' '+x.regime).toLowerCase().includes(q))&&(!side||x.side===side)).slice(0,150);$('#tradeBody').innerHTML=rows.map(x=>{const costs=Number(x.feesEUR||0)+Number(x.spreadEUR||0)+Number(x.slippageEUR||0)+Number(x.fundingEUR||0);return `<tr><td><b>${x.strategyId}</b><br><small>${esc(x.strategy)}</small></td><td>${esc(String(x.entryTime).slice(0,16).replace('T',' '))}</td><td class="${x.side==='LONG'?'pos':'neg'}">${x.side}</td><td>${num(x.entry,1)}</td><td>${num(x.exit,1)}</td><td>${num(x.leverage,2)}×</td><td>${euro(x.notionalEUR)}</td><td class="${cls(x.netPnLEUR)}">${euro(x.netPnLEUR)}</td><td>${euro(costs)}</td><td>${num(x.durationMin,0)}m</td><td>${esc(x.exitReason)}</td><td>${esc(x.regime)}</td></tr>`}).join('');}
function renderQuality(){const q=M.quality||{},f=M.fingerprint||{};$('#qualityScore').textContent=(q.score??'—')+'/100';$('#qualityKpis').innerHTML=kpi('Rows',num(q.rows,0),'1-minute bars')+kpi('Missing minutes',num(q.missingMinutes,0),'Continuity',q.missingMinutes?'neg':'pos')+kpi('Duplicates',num(q.duplicateTimestamps,0),'Timestamp duplicates',q.duplicateTimestamps?'neg':'pos')+kpi('Null values',num(q.nullValues,0),'All columns',q.nullValues?'neg':'pos')+kpi('Invalid OHLC',num(q.invalidOHLC,0),'Price sanity',q.invalidOHLC?'neg':'pos');$('#fingerprint').innerHTML=Object.entries(f).map(([k,v])=>`<div><b>${esc(k)}</b>: ${esc(v)}</div>`).join('');const notes=q.notes||[];$('#notes').innerHTML=notes.length?notes.map(x=>`<div class="note">${esc(x)}</div>`).join(''):'<div class="note">No audit notes.</div>';}
function boot(){bootNav();setupFilters();renderDashboard();renderMatrix();renderTrades();renderQuality();renderDetail(S[0]?.strategy_id);renderLeverage(S[0]?.strategy_id);}
boot();
